/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Achievement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AchievementTests
    {
        // TODO uncomment below to declare an instance variable for Achievement
        //private Achievement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Achievement
            //instance = new Achievement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Achievement
        /// </summary>
        [Test]
        public void AchievementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Achievement
            //Assert.IsInstanceOf(typeof(Achievement), instance);
        }


        /// <summary>
        /// Test the property 'AchievementId'
        /// </summary>
        [Test]
        public void AchievementIdTest()
        {
            // TODO unit test for the property 'AchievementId'
        }
        /// <summary>
        /// Test the property 'AchievementTitle'
        /// </summary>
        [Test]
        public void AchievementTitleTest()
        {
            // TODO unit test for the property 'AchievementTitle'
        }
        /// <summary>
        /// Test the property 'AchievementDesc'
        /// </summary>
        [Test]
        public void AchievementDescTest()
        {
            // TODO unit test for the property 'AchievementDesc'
        }
        /// <summary>
        /// Test the property 'AchievementPoint'
        /// </summary>
        [Test]
        public void AchievementPointTest()
        {
            // TODO unit test for the property 'AchievementPoint'
        }
        /// <summary>
        /// Test the property 'RelatedTitles'
        /// </summary>
        [Test]
        public void RelatedTitlesTest()
        {
            // TODO unit test for the property 'RelatedTitles'
        }

    }

}
