/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AchievementGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AchievementGroupTests
    {
        // TODO uncomment below to declare an instance variable for AchievementGroup
        //private AchievementGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AchievementGroup
            //instance = new AchievementGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AchievementGroup
        /// </summary>
        [Test]
        public void AchievementGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AchievementGroup
            //Assert.IsInstanceOf(typeof(AchievementGroup), instance);
        }


        /// <summary>
        /// Test the property 'SubGroups'
        /// </summary>
        [Test]
        public void SubGroupsTest()
        {
            // TODO unit test for the property 'SubGroups'
        }
        /// <summary>
        /// Test the property 'Achievements'
        /// </summary>
        [Test]
        public void AchievementsTest()
        {
            // TODO unit test for the property 'Achievements'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'AchievementsCount'
        /// </summary>
        [Test]
        public void AchievementsCountTest()
        {
            // TODO unit test for the property 'AchievementsCount'
        }
        /// <summary>
        /// Test the property 'AchievementPoints'
        /// </summary>
        [Test]
        public void AchievementPointsTest()
        {
            // TODO unit test for the property 'AchievementPoints'
        }

    }

}
