/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Hit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HitTests
    {
        // TODO uncomment below to declare an instance variable for Hit
        //private Hit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Hit
            //instance = new Hit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Hit
        /// </summary>
        [Test]
        public void HitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Hit
            //Assert.IsInstanceOf(typeof(Hit), instance);
        }


        /// <summary>
        /// Test the property 'Attacker'
        /// </summary>
        [Test]
        public void AttackerTest()
        {
            // TODO unit test for the property 'Attacker'
        }
        /// <summary>
        /// Test the property 'Victim'
        /// </summary>
        [Test]
        public void VictimTest()
        {
            // TODO unit test for the property 'Victim'
        }
        /// <summary>
        /// Test the property 'HitTimestamp'
        /// </summary>
        [Test]
        public void HitTimestampTest()
        {
            // TODO unit test for the property 'HitTimestamp'
        }
        /// <summary>
        /// Test the property 'HitDamage'
        /// </summary>
        [Test]
        public void HitDamageTest()
        {
            // TODO unit test for the property 'HitDamage'
        }
        /// <summary>
        /// Test the property 'HitDistance'
        /// </summary>
        [Test]
        public void HitDistanceTest()
        {
            // TODO unit test for the property 'HitDistance'
        }
        /// <summary>
        /// Test the property 'HitAreaId'
        /// </summary>
        [Test]
        public void HitAreaIdTest()
        {
            // TODO unit test for the property 'HitAreaId'
        }
        /// <summary>
        /// Test the property 'AttackerActiveItem'
        /// </summary>
        [Test]
        public void AttackerActiveItemTest()
        {
            // TODO unit test for the property 'AttackerActiveItem'
        }
        /// <summary>
        /// Test the property 'VictimActiveItem'
        /// </summary>
        [Test]
        public void VictimActiveItemTest()
        {
            // TODO unit test for the property 'VictimActiveItem'
        }
        /// <summary>
        /// Test the property 'AttackerPosition'
        /// </summary>
        [Test]
        public void AttackerPositionTest()
        {
            // TODO unit test for the property 'AttackerPosition'
        }
        /// <summary>
        /// Test the property 'VictimPosition'
        /// </summary>
        [Test]
        public void VictimPositionTest()
        {
            // TODO unit test for the property 'VictimPosition'
        }

    }

}
