/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing HuntForWeapon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HuntForWeaponTests
    {
        // TODO uncomment below to declare an instance variable for HuntForWeapon
        //private HuntForWeapon instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HuntForWeapon
            //instance = new HuntForWeapon();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HuntForWeapon
        /// </summary>
        [Test]
        public void HuntForWeaponInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" HuntForWeapon
            //Assert.IsInstanceOf(typeof(HuntForWeapon), instance);
        }


        /// <summary>
        /// Test the property 'PlayerSteamId'
        /// </summary>
        [Test]
        public void PlayerSteamIdTest()
        {
            // TODO unit test for the property 'PlayerSteamId'
        }
        /// <summary>
        /// Test the property 'PlayerName'
        /// </summary>
        [Test]
        public void PlayerNameTest()
        {
            // TODO unit test for the property 'PlayerName'
        }
        /// <summary>
        /// Test the property 'PickupTime'
        /// </summary>
        [Test]
        public void PickupTimeTest()
        {
            // TODO unit test for the property 'PickupTime'
        }
        /// <summary>
        /// Test the property 'ConnectionTime'
        /// </summary>
        [Test]
        public void ConnectionTimeTest()
        {
            // TODO unit test for the property 'ConnectionTime'
        }
        /// <summary>
        /// Test the property 'ItemNotificationId'
        /// </summary>
        [Test]
        public void ItemNotificationIdTest()
        {
            // TODO unit test for the property 'ItemNotificationId'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Test]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }
        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Test]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }

    }

}
