/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PlayerPosition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerPositionTests
    {
        // TODO uncomment below to declare an instance variable for PlayerPosition
        //private PlayerPosition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlayerPosition
            //instance = new PlayerPosition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlayerPosition
        /// </summary>
        [Test]
        public void PlayerPositionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PlayerPosition
            //Assert.IsInstanceOf(typeof(PlayerPosition), instance);
        }


        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Z'
        /// </summary>
        [Test]
        public void ZTest()
        {
            // TODO unit test for the property 'Z'
        }

    }

}
