/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RelatedTitle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RelatedTitleTests
    {
        // TODO uncomment below to declare an instance variable for RelatedTitle
        //private RelatedTitle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedTitle
            //instance = new RelatedTitle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedTitle
        /// </summary>
        [Test]
        public void RelatedTitleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RelatedTitle
            //Assert.IsInstanceOf(typeof(RelatedTitle), instance);
        }


        /// <summary>
        /// Test the property 'TitleId'
        /// </summary>
        [Test]
        public void TitleIdTest()
        {
            // TODO unit test for the property 'TitleId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'RequiredAchievements'
        /// </summary>
        [Test]
        public void RequiredAchievementsTest()
        {
            // TODO unit test for the property 'RequiredAchievements'
        }

    }

}
