/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Wipe
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WipeTests
    {
        // TODO uncomment below to declare an instance variable for Wipe
        //private Wipe instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Wipe
            //instance = new Wipe();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Wipe
        /// </summary>
        [Test]
        public void WipeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Wipe
            //Assert.IsInstanceOf(typeof(Wipe), instance);
        }


        /// <summary>
        /// Test the property 'WipeId'
        /// </summary>
        [Test]
        public void WipeIdTest()
        {
            // TODO unit test for the property 'WipeId'
        }
        /// <summary>
        /// Test the property 'WipeStart'
        /// </summary>
        [Test]
        public void WipeStartTest()
        {
            // TODO unit test for the property 'WipeStart'
        }
        /// <summary>
        /// Test the property 'WipeEnd'
        /// </summary>
        [Test]
        public void WipeEndTest()
        {
            // TODO unit test for the property 'WipeEnd'
        }

    }

}
