/* 
 * GamingEventApi API
 *
 * GamingEventApi API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CombatKill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CombatKillTests
    {
        // TODO uncomment below to declare an instance variable for CombatKill
        //private CombatKill instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CombatKill
            //instance = new CombatKill();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CombatKill
        /// </summary>
        [Test]
        public void CombatKillInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CombatKill
            //Assert.IsInstanceOf(typeof(CombatKill), instance);
        }


        /// <summary>
        /// Test the property 'Victim'
        /// </summary>
        [Test]
        public void VictimTest()
        {
            // TODO unit test for the property 'Victim'
        }
        /// <summary>
        /// Test the property 'Killer'
        /// </summary>
        [Test]
        public void KillerTest()
        {
            // TODO unit test for the property 'Killer'
        }
        /// <summary>
        /// Test the property 'Assists'
        /// </summary>
        [Test]
        public void AssistsTest()
        {
            // TODO unit test for the property 'Assists'
        }
        /// <summary>
        /// Test the property 'Hits'
        /// </summary>
        [Test]
        public void HitsTest()
        {
            // TODO unit test for the property 'Hits'
        }

    }

}
