/* 
 * Blackhawk API
 *
 * Blackhawk API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Title
    /// </summary>
    [DataContract]
    public partial class Title :  IEquatable<Title>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Title" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Title() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Title" /> class.
        /// </summary>
        /// <param name="titleId">titleId (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="titleColor">titleColor (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="requiredAchievements">requiredAchievements.</param>
        public Title(int titleId = default(int), string title = default(string), string titleColor = default(string), string description = default(string), List<int> requiredAchievements = default(List<int>))
        {
            // to ensure "titleId" is required (not null)
            if (titleId == null)
            {
                throw new InvalidDataException("titleId is a required property for Title and cannot be null");
            }
            else
            {
                this.TitleId = titleId;
            }
            
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new InvalidDataException("title is a required property for Title and cannot be null");
            }
            else
            {
                this._Title = title;
            }
            
            // to ensure "titleColor" is required (not null)
            if (titleColor == null)
            {
                throw new InvalidDataException("titleColor is a required property for Title and cannot be null");
            }
            else
            {
                this.TitleColor = titleColor;
            }
            
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for Title and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            
            this.RequiredAchievements = requiredAchievements;
        }
        
        /// <summary>
        /// Gets or Sets TitleId
        /// </summary>
        [DataMember(Name="title_id", EmitDefaultValue=true)]
        public int TitleId { get; set; }

        /// <summary>
        /// Gets or Sets _Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=true)]
        public string _Title { get; set; }

        /// <summary>
        /// Gets or Sets TitleColor
        /// </summary>
        [DataMember(Name="title_color", EmitDefaultValue=true)]
        public string TitleColor { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets RequiredAchievements
        /// </summary>
        [DataMember(Name="required_achievements", EmitDefaultValue=false)]
        public List<int> RequiredAchievements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Title {\n");
            sb.Append("  TitleId: ").Append(TitleId).Append("\n");
            sb.Append("  _Title: ").Append(_Title).Append("\n");
            sb.Append("  TitleColor: ").Append(TitleColor).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  RequiredAchievements: ").Append(RequiredAchievements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Title);
        }

        /// <summary>
        /// Returns true if Title instances are equal
        /// </summary>
        /// <param name="input">Instance of Title to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Title input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TitleId == input.TitleId ||
                    (this.TitleId != null &&
                    this.TitleId.Equals(input.TitleId))
                ) && 
                (
                    this._Title == input._Title ||
                    (this._Title != null &&
                    this._Title.Equals(input._Title))
                ) && 
                (
                    this.TitleColor == input.TitleColor ||
                    (this.TitleColor != null &&
                    this.TitleColor.Equals(input.TitleColor))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.RequiredAchievements == input.RequiredAchievements ||
                    this.RequiredAchievements != null &&
                    input.RequiredAchievements != null &&
                    this.RequiredAchievements.SequenceEqual(input.RequiredAchievements)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TitleId != null)
                    hashCode = hashCode * 59 + this.TitleId.GetHashCode();
                if (this._Title != null)
                    hashCode = hashCode * 59 + this._Title.GetHashCode();
                if (this.TitleColor != null)
                    hashCode = hashCode * 59 + this.TitleColor.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.RequiredAchievements != null)
                    hashCode = hashCode * 59 + this.RequiredAchievements.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
