/* 
 * GamingEventApi API
 *
 * GamingEventApi API for the rust server
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jonas-lt@live.dk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PlayerAchievement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerAchievementTests
    {
        // TODO uncomment below to declare an instance variable for PlayerAchievement
        //private PlayerAchievement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlayerAchievement
            //instance = new PlayerAchievement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlayerAchievement
        /// </summary>
        [Test]
        public void PlayerAchievementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PlayerAchievement
            //Assert.IsInstanceOf(typeof(PlayerAchievement), instance);
        }


        /// <summary>
        /// Test the property 'ReceiveDate'
        /// </summary>
        [Test]
        public void ReceiveDateTest()
        {
            // TODO unit test for the property 'ReceiveDate'
        }
        /// <summary>
        /// Test the property 'Achievement'
        /// </summary>
        [Test]
        public void AchievementTest()
        {
            // TODO unit test for the property 'Achievement'
        }

    }

}
