name: Main release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/GamingAPI/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - run: dotnet build --configuration Release Oxide.Ext.GamingApi
      - name: Create the package
        run: dotnet pack --configuration Release Oxide.Ext.GamingApi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Oxide.Ext.GamingApi/bin/Release/NATS.Client.dll
            Oxide.Ext.GamingApi/bin/Release/Newtonsoft.Json.dll
            Oxide.Ext.GamingApi/bin/Release/Oxide.Ext.GamingApi.dll
            Oxide.Ext.GamingApi/bin/Release/RustGameAPI.dll