name: Release
env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/GamingAPI/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: dotnet restore
      - name: 'Automated Version Bump'
        uses: 'jonaslagoni/gh-action-dotnet-bump@main'
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          skip-tag: 'true'
          skip-commit: 'true'
          path-to-file: './Oxide.Ext.GamingApi/Oxide.Ext.GamingApi.csproj'
          release-commit-message-regex: 'chore\(release\): v{{version}}'
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        run: dotnet build --configuration Release Oxide.Ext.GamingApi --no-restore
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Create the nuget package
        run: dotnet pack --configuration Release Oxide.Ext.GamingApi --no-restore
      - name: Create GH release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version_bump.outputs.newVersion}}
          release_name: Release v${{steps.version_bump.outputs.newVersion}}
          body: |
            New server extension release v${{steps.version_bump.outputs.newVersion}}
          draft: false
          prerelease: false
      - uses: xresloader/upload-to-github-release@v1.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./release/*" # Separated by ;
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
          draft: false
          update_latest_release: true
      - if: steps.version_bump.outputs.wasBumped == 'true' 
        name: Publish the nuget package to GitHub registry
        run: dotnet nuget push Oxide.Ext.GamingApi\bin\Release\Oxide.Ext.GamingApi.*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}} 
      - if: steps.version_bump.outputs.wasBumped == 'true'
        name: Create Pull Request with bumped version
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_TOKEN }}'
          commit-message: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          committer: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          author: '${{env.GH_USER}} ${{env.GH_EMAIL}}'
          title: 'chore(release): v${{steps.version_bump.outputs.newVersion}}'
          body: Version bump
          branch: 'version-bump/v${{steps.version_bump.outputs.newVersion}}'
